<?php

namespace App\Console\Commands;

use App\Models\GeneratedInvoice;
use App\Models\IncomingEmail;
use App\Services\MicrosoftGraphService;
use App\Services\ExchangeRateService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use GuzzleHttp\Client as GuzzleClient;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;

class GenerateDailyReportCommand extends Command
{
    protected $signature = 'report:daily {--date=} {--upload} {--email=}';
    protected $description = 'Generate daily invoice report and upload to OneDrive';

    protected $exchangeRateService;

    public function __construct(ExchangeRateService $exchangeRateService)
    {
        parent::__construct();
        $this->exchangeRateService = $exchangeRateService;
    }

    public function handle()
    {
        $date = $this->option('date') ?? date('Y-m-d');
        $upload = $this->option('upload') ?? true;
        $emailTo = $this->option('email') ?? 'pradeep.kumar@bcdtravel.lk';
        
        $this->info("📊 Generating daily report for: {$date}");
        
        try {
            $filePath = $this->generateReport($date);
            
            if (!$filePath) {
                $this->error('❌ Failed to generate report');
                return 1;
            }
            
            $this->info("✅ Report generated: {$filePath}");
            
            $this->sendEmailWithAttachment($filePath, $date, $emailTo);
            
            if ($upload) {
                $uploadSuccess = $this->uploadToOneDrive($filePath, $date);
                if ($uploadSuccess) {
                    $this->info("✅ Uploaded to OneDrive successfully");
                }
            }
            
            Log::info("✅ Daily report generated for {$date}: {$filePath}");
            return 0;
            
        } catch (\Exception $e) {
            $this->error('❌ Error: ' . $e->getMessage());
            Log::error('Daily report failed: ' . $e->getMessage());
            return 1;
        }
    }

    protected function sendEmailWithAttachment($filePath, $date, $to)
    {
        try {
            $formattedDate = date('d/m/Y', strtotime($date));
            $filename = basename($filePath);
            
            $subject = "📊 Daily Invoice Report - {$formattedDate}";
            
            $message = "Dear Sir,\n\n";
            $message .= "Please find attached the daily invoice report for {$formattedDate}.\n\n";
            $message .= "📄 File: {$filename}\n";
            $message .= "📅 Date: {$formattedDate}\n\n";
            
            if ($this->option('upload')) {
                $message .= "📁 This report has also been uploaded to the shared OneDrive folder.\n\n";
            }
            
            $message .= "─────────────────────────────\n";
            $message .= "Generated by: Invoice Processing System\n";
            $message .= "Time: " . now()->format('d/m/Y H:i:s') . "\n";
            $message .= "─────────────────────────────\n";
            $message .= "This is an automated email. Please do not reply.\n";

            Mail::raw($message, function ($mail) use ($to, $subject, $filePath, $filename) {
                $mail->to($to)
                     ->subject($subject)
                     ->attach($filePath, [
                         'as' => $filename,
                         'mime' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                     ]);
            });

            $this->info("📧 Email with attachment sent to: {$to}");
            Log::info("Daily report email with attachment sent to: {$to}");

        } catch (\Exception $e) {
            $this->error("❌ Failed to send email: " . $e->getMessage());
            Log::error("Failed to send email with attachment: " . $e->getMessage());
        }
    }

    protected function sanitizeString($string)
    {
        if (is_null($string)) {
            return '';
        }
        
        if (!mb_check_encoding($string, 'UTF-8')) {
            $string = mb_convert_encoding($string, 'UTF-8', 'auto');
        }
        
        $string = preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/u', '', $string);
        return trim($string);
    }

    /**
     * ✅ Convert any currency to USD
     */
    protected function convertToUSD($amount, $currency)
    {
        // If amount is 0 or null, return 0
        if (empty($amount) || $amount == 0) {
            return 0;
        }

        // If already USD, return the amount as-is
        if (strtoupper($currency) === 'USD') {
            return $amount;
        }

        try {
            // Get rate from currency to INR using ExchangeRateService
            $inrRate = $this->exchangeRateService->getRate($currency, 'INR');
            
            // Get USD to INR rate
            $usdToInrRate = $this->exchangeRateService->getUsdToInrRate();
            
            // Convert to INR first, then to USD
            $amountInInr = $amount * $inrRate;
            $usdAmount = $amountInInr / $usdToInrRate;
            
            Log::info("USD Conversion: {$amount} {$currency} → {$amountInInr} INR → {$usdAmount} USD (Rate: {$inrRate}, USD/INR: {$usdToInrRate})");
            
            return $usdAmount;
            
        } catch (\Exception $e) {
            Log::warning("Could not get exchange rate for currency: {$currency}, Error: " . $e->getMessage());
            
            // ✅ Fallback: Direct rates to USD
            $fallbackRates = [
                'LKR' => 0.0030,   // 1 LKR = 0.0030 USD
                'INR' => 0.0120,   // 1 INR = 0.0120 USD
                'EUR' => 1.09,
                'GBP' => 1.27,
                'SGD' => 0.74,
                'MYR' => 0.21,
                'VND' => 0.000039,
                'AED' => 0.27,
                'SAR' => 0.27,
                'QAR' => 0.27,
                'KWD' => 3.26,
                'BHD' => 2.65,
            ];

            $rate = $fallbackRates[strtoupper($currency)] ?? 1;
            $usdAmount = $amount * $rate;
            
            Log::info("USD Conversion (fallback): {$amount} {$currency} → {$usdAmount} USD");
            
            return $usdAmount;
        }
    }

    protected function generateReport($date)
    {
        $invoices = GeneratedInvoice::with('email')
            ->whereDate('created_at', $date)
            ->orderBy('created_at', 'asc')
            ->get();
        
        if ($invoices->isEmpty()) {
            $this->info("📭 No invoices found for {$date}");
            return $this->generateEmptyReport($date);
        }
        
        $latestInvoices = $this->getLatestRevisions($invoices);
        
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        
        // ✅ Headers: Added USD Amount column
        $headers = [
            'S.No', 
            'Invoice #', 
            'Tour Ref', 
            'Agent Name', 
            'Agent ID',
            'Guest Name',
            'Amount', 
            'Currency',
            'USD Amount',     // ← NEW COLUMN - USD equivalent for all invoices
            'File Handler', 
            'Tour Start Date',
            'Travel Date', 
            'Sales Person', 
            'GST No', 
            'Revision', 
            'Created At'
        ];
        
        $col = 'A';
        foreach ($headers as $header) {
            $sheet->setCellValue($col . '1', $this->sanitizeString($header));
            $sheet->getStyle($col . '1')->getFont()->setBold(true);
            $col++;
        }
        
        $row = 2;
        $sno = 1;
        $totalAmount = 0;
        $totalUSD = 0;
        
        foreach ($latestInvoices as $invoice) {
            $col = 'A';
            $amount = $invoice->grand_total ?? 0;
            $currency = $invoice->currency ?? 'USD';
            
            // ✅ Convert to USD
            $usdAmount = $this->convertToUSD($amount, $currency);
            
            $sheet->setCellValue($col++ . $row, $sno++);
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($invoice->invoice_number));
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($invoice->tour_ref));
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($invoice->customer_name));
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($invoice->email->reference_no ?? 'NA'));
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($invoice->guest_name));
            $sheet->setCellValue($col++ . $row, $amount);
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($currency));
            $sheet->setCellValue($col++ . $row, number_format($usdAmount, 2));    // ✅ USD Amount
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($invoice->email->file_handler ?? 'NA'));
            $sheet->setCellValue($col++ . $row, $invoice->email->travel_start_date ? date('d/m/Y', strtotime($invoice->email->travel_start_date)) : 'NA');
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($this->getTravelDates($invoice->email)));
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($invoice->sales_person ?? 'NA'));
            $sheet->setCellValue($col++ . $row, $this->sanitizeString($invoice->gst_number ?? 'NA'));
            $sheet->setCellValue($col++ . $row, $invoice->is_revision ? 'R' . $invoice->revision_number : 'Original');
            $sheet->setCellValue($col++ . $row, $invoice->created_at->format('d/m/Y H:i'));
            
            $totalAmount += $amount;
            $totalUSD += $usdAmount;
            $row++;
        }
        
        // ✅ Summary Row
        $row++;
        $sheet->setCellValue('A' . $row, 'TOTAL');
        $sheet->setCellValue('G' . $row, $totalAmount);        // Amount column (G)
        $sheet->setCellValue('I' . $row, number_format($totalUSD, 2));   // USD Amount column (I)
        $sheet->getStyle('A' . $row . ':P' . $row)->getFont()->setBold(true);
        
        // ✅ Auto-size all columns (A to P = 16 columns)
        foreach (range('A', 'P') as $col) {
            $sheet->getColumnDimension($col)->setAutoSize(true);
        }
        
        $filename = 'daily_invoice_report_' . date('Y-m-d', strtotime($date)) . '.xlsx';
        $directory = storage_path('app/public/reports/daily');
        
        if (!file_exists($directory)) {
            mkdir($directory, 0755, true);
        }
        
        $filePath = $directory . '/' . $filename;
        $writer = new Xlsx($spreadsheet);
        $writer->setPreCalculateFormulas(false);
        $writer->save($filePath);
        
        return $filePath;
    }

    protected function generateEmptyReport($date)
    {
        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        
        $sheet->setCellValue('A1', 'No invoices generated on ' . date('d/m/Y', strtotime($date)));
        $sheet->getStyle('A1')->getFont()->setBold(true);
        
        $filename = 'daily_invoice_report_' . date('Y-m-d', strtotime($date)) . '.xlsx';
        $directory = storage_path('app/public/reports/daily');
        
        if (!file_exists($directory)) {
            mkdir($directory, 0755, true);
        }
        
        $filePath = $directory . '/' . $filename;
        $writer = new Xlsx($spreadsheet);
        $writer->save($filePath);
        
        return $filePath;
    }

    protected function getLatestRevisions($invoices)
    {
        $grouped = [];
        $baseKeysWithRevisions = [];
        
        // First pass: Find which invoices have revisions
        foreach ($invoices as $invoice) {
            $baseKey = $this->getInvoiceBaseNumber($invoice);
            if ($invoice->is_revision) {
                $baseKeysWithRevisions[$baseKey] = true;
            }
        }
        
        // Second pass: For each invoice, decide what to keep
        foreach ($invoices as $invoice) {
            $baseKey = $this->getInvoiceBaseNumber($invoice);
            
            // Case 1: This invoice has revisions (there's at least one revision for this base)
            if (isset($baseKeysWithRevisions[$baseKey])) {
                // If this is the original (is_revision = false), SKIP it
                if (!$invoice->is_revision) {
                    continue;
                }
                
                // If this is a revision, keep only the latest one
                if (!isset($grouped[$baseKey]) || $invoice->revision_number > $grouped[$baseKey]->revision_number) {
                    $grouped[$baseKey] = $invoice;
                }
            } 
            // Case 2: No revisions for this invoice, keep the original
            else {
                // Only keep if it's the original (no revision suffix)
                if (!$invoice->is_revision) {
                    $grouped[$baseKey] = $invoice;
                }
            }
        }
        
        return collect(array_values($grouped));
    }

    protected function getInvoiceBaseNumber($invoice)
    {
        if ($invoice->original_invoice_number) {
            return $invoice->original_invoice_number;
        }
        
        $base = $invoice->invoice_number;
        $base = preg_replace('/_R\d+\/R\d+$/', '', $base);
        $base = preg_replace('/_R\d+_R\d+$/', '', $base);
        $base = preg_replace('/\/R\d+$/', '', $base);
        $base = preg_replace('/R\d+$/', '', $base);
        $base = preg_replace('/_R\d+$/', '', $base);
        
        return $base;
    }

    protected function getTravelDates($email)
    {
        if (!$email) return 'NA';
        
        $start = $email->travel_start_date ? date('d/m/Y', strtotime($email->travel_start_date)) : '';
        $end = $email->travel_end_date ? date('d/m/Y', strtotime($email->travel_end_date)) : '';
        
        if ($start && $end && $start !== $end) {
            return $start . ' - ' . $end;
        }
        return $start ?: 'NA';
    }

    protected function uploadToOneDrive($filePath, $date)
    {
        try {
            $filename = basename($filePath);
            $folderPath = env('ONEDRIVE_FOLDER_PATH', '/Invoice Report/');
            $userEmail = env('ONEDRIVE_USER', env('GRAPH_INVOICE_USER'));
            
            $this->info("📤 Uploading to OneDrive: {$folderPath}{$filename}");
            $this->info("📧 Using account: {$userEmail}");
            
            if (!file_exists($filePath) || !is_readable($filePath)) {
                $this->error("❌ File not found or not readable: {$filePath}");
                return false;
            }
            
            $content = file_get_contents($filePath);
            
            if (empty($content)) {
                $this->error("❌ File is empty: {$filePath}");
                return false;
            }
            
            $this->info("📄 File size: " . number_format(strlen($content)) . " bytes");
            
            $graphService = new MicrosoftGraphService();
            
            $reflection = new \ReflectionProperty($graphService, 'accessToken');
            $reflection->setAccessible(true);
            $token = $reflection->getValue($graphService);
            
            if (empty($token)) {
                $this->error("❌ No access token available.");
                Log::error("OneDrive upload failed: No access token");
                return false;
            }
            
            $encodedFolder = str_replace(' ', '%20', $folderPath);
            $uploadUrl = "https://graph.microsoft.com/v1.0/users/{$userEmail}/drive/root:{$encodedFolder}{$filename}:/content";
            
            $this->info("📡 Uploading to: " . str_replace($userEmail, '***', $uploadUrl));
            
            $client = new \GuzzleHttp\Client([
                'timeout' => 120,
                'verify' => false,
            ]);
            
            $response = $client->put($uploadUrl, [
                'headers' => [
                    'Authorization' => 'Bearer ' . $token,
                    'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                ],
                'body' => $content,
            ]);
            
            if ($response->getStatusCode() >= 200 && $response->getStatusCode() < 300) {
                $this->info("✅ Uploaded to OneDrive: {$folderPath}{$filename}");
                Log::info("Uploaded daily report to OneDrive: {$folderPath}{$filename}");
                
                $responseBody = $response->getBody()->getContents();
                $fileData = json_decode($responseBody, true);
                if (isset($fileData['webUrl'])) {
                    $this->info("🔗 File URL: " . $fileData['webUrl']);
                }
                
                return true;
            } else {
                $this->error("❌ Upload failed: Status " . $response->getStatusCode());
                $this->error("❌ Response: " . $response->getBody()->getContents());
                Log::error("OneDrive upload failed: " . $response->getBody()->getContents());
                
                $this->info("🔄 Trying alternative endpoint...");
                return $this->uploadToOneDriveAlternative($filePath, $date);
            }
            
        } catch (\Exception $e) {
            $this->error("❌ Upload error: " . $e->getMessage());
            Log::error("OneDrive upload error: " . $e->getMessage());
            return false;
        }
    }

    protected function uploadToOneDriveAlternative($filePath, $date)
    {
        try {
            $filename = basename($filePath);
            $folderPath = env('ONEDRIVE_FOLDER_PATH', '/Invoice Report/');
            
            $graphService = new MicrosoftGraphService();
            $reflection = new \ReflectionProperty($graphService, 'accessToken');
            $reflection->setAccessible(true);
            $token = $reflection->getValue($graphService);
            
            if (empty($token)) {
                $this->error("❌ No token for alternative upload");
                return false;
            }
            
            $content = file_get_contents($filePath);
            $encodedFolder = str_replace(' ', '%20', $folderPath);
            $uploadUrl = "https://graph.microsoft.com/v1.0/me/drive/root:{$encodedFolder}{$filename}:/content";
            
            $client = new \GuzzleHttp\Client([
                'timeout' => 120,
                'verify' => false,
            ]);
            
            $response = $client->put($uploadUrl, [
                'headers' => [
                    'Authorization' => 'Bearer ' . $token,
                    'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                ],
                'body' => $content,
            ]);
            
            if ($response->getStatusCode() >= 200 && $response->getStatusCode() < 300) {
                $this->info("✅ Uploaded to OneDrive (alternative): {$folderPath}{$filename}");
                Log::info("Uploaded daily report to OneDrive (alt): {$folderPath}{$filename}");
                return true;
            } else {
                $this->error("❌ Alternative upload failed: " . $response->getBody()->getContents());
                return false;
            }
            
        } catch (\Exception $e) {
            $this->error("❌ Alternative upload error: " . $e->getMessage());
            return false;
        }
    }
}