<?php
// database/seeders/SriLankaDriverBankDetailsSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\DriverBankDetail;

class SriLankaDriverBankDetailsSeeder extends Seeder
{
    public function run()
    {
        $drivers = [
            ['payee_name' => 'Jerry Tours', 'account_number' => '0083784945', 'bank_branch' => 'Bank of Ceylon Ja-Ela'],
            ['payee_name' => 'M O D Silva', 'account_number' => '121252387283', 'bank_branch' => 'Sampath Bank Gampaha'],
            ['payee_name' => 'Mudiyanselage Don Camalka Dilshan', 'account_number' => '8310032407', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'N M Ishan', 'account_number' => '8013425193', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'A A N Nayanajith', 'account_number' => '161012871119001', 'bank_branch' => 'Seylan Bank Dankotuwa'],
            ['payee_name' => 'A A S Dilhara', 'account_number' => '8004960757', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'A A Silva', 'account_number' => '107953052075', 'bank_branch' => 'Sampath Bank Aluthgama'],
            ['payee_name' => 'A D S P Kumara', 'account_number' => '8000626176', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'A R C S Bandara', 'account_number' => '8113017386', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'A.D.S.P. Kumara', 'account_number' => '8000626176', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'A.K.J.G. Rathnasekara', 'account_number' => '110657873092', 'bank_branch' => 'Sampath Bank Matugama'],
            ['payee_name' => 'A.T.A Wijayasoma', 'account_number' => '1000010501', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'A.U.M.P.K Lankathilaka', 'account_number' => '224020056674', 'bank_branch' => 'Hatton National Bank Kurunagala'],
            ['payee_name' => 'Achini Sahara', 'account_number' => '200600084947', 'bank_branch' => 'Nations Trust Bank Ja-ela'],
            ['payee_name' => 'As Ekanayaka', 'account_number' => '102152866848', 'bank_branch' => 'Sampath Bank Anuradhapura'],
            ['payee_name' => 'B A I Mendis', 'account_number' => '82125379', 'bank_branch' => 'Bank of Ceylon Gampaha'],
            ['payee_name' => 'B E R Kumara', 'account_number' => '147020124290', 'bank_branch' => 'Hatton National Bank Nawala'],
            ['payee_name' => 'B J S D Mendis', 'account_number' => '230010007597', 'bank_branch' => 'Hatton National Bank Ekala'],
            ['payee_name' => 'C A H M C J Herath', 'account_number' => '119754156278', 'bank_branch' => 'Sampath Bank Maho'],
            ['payee_name' => 'C M L T Pebera', 'account_number' => '8710030639', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'C M L T Rebera', 'account_number' => '8710030639', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'C P K Ranathunga', 'account_number' => '85949666', 'bank_branch' => 'Bank of Ceylon Suriyawewa'],
            ['payee_name' => 'C.S Dissanayaka', 'account_number' => '8253660901', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Chandrathilka', 'account_number' => '8670025551', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'D A S Silva', 'account_number' => '034020221462', 'bank_branch' => 'Hatton National Bank Kalutara'],
            ['payee_name' => 'D Anusha Chaminda De Zoysa', 'account_number' => '8011089120', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'D D Nilantha', 'account_number' => '8023083932', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'D G S Kumarathunga', 'account_number' => '100654922828', 'bank_branch' => 'Sampath Bank Kurunegala'],
            ['payee_name' => 'D G S Prasanna', 'account_number' => '8020585262', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'D M D G B S Dasanayake', 'account_number' => '701020131090', 'bank_branch' => 'Hatton National Bank Nawam Mawatha'],
            ['payee_name' => 'D M P M Dasanayake', 'account_number' => '8018562879', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Damith Aravinda', 'account_number' => '022032455134101', 'bank_branch' => 'Seylan Bank Grandpass'],
            ['payee_name' => 'Diyakawa Water Sport Center', 'account_number' => '101000922887', 'bank_branch' => 'NDB Bank Ltd Aluthgama'],
            ['payee_name' => 'Don Amesh Dulal Jayamanne', 'account_number' => '200070138980', 'bank_branch' => 'Nations Trust Bank Negombo'],
            ['payee_name' => 'E D T Kusumsiri', 'account_number' => '6619897', 'bank_branch' => 'Bank of Ceylon Central Bus Stand'],
            ['payee_name' => 'E H S De Silva', 'account_number' => '8022390680', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Flamingos Safari Tours', 'account_number' => '1124015383', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'G.L.D.S.Perera', 'account_number' => '119020201417', 'bank_branch' => 'Hatton National Bank Kandana'],
            ['payee_name' => 'H A G S Karunajeewa', 'account_number' => '238200190027679', 'bank_branch' => 'Peoples Bank Gonagaladeniya'],
            ['payee_name' => 'H A P Sanjitha', 'account_number' => '8836165101', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'H G H Appuhamy', 'account_number' => '8245000111', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'H M U K Wijeratne', 'account_number' => '1339120', 'bank_branch' => 'Bank of Ceylon Malkaduwawa'],
            ['payee_name' => 'H S M De Zoysa', 'account_number' => '115510894512', 'bank_branch' => 'NDB Bank Ltd / Shangri-La Colombo M'],
            ['payee_name' => 'H W A Thiwanka Madushan', 'account_number' => '75714517', 'bank_branch' => 'Bank of Ceylon Akuressa'],
            ['payee_name' => 'H. M. I De Silva', 'account_number' => '200250003110', 'bank_branch' => 'Nations Trust Bank Havelock Town'],
            ['payee_name' => 'H.A.Shachira Pathum Chandrasiri', 'account_number' => '025020444627', 'bank_branch' => 'Hatton National Bank Nittambuwa'],
            ['payee_name' => 'H.G.N.Kithsiri', 'account_number' => '240020041076', 'bank_branch' => 'Hatton National Bank Kalutara'],
            ['payee_name' => 'H.M.A.C.Bandara', 'account_number' => '8930025474', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Himaya Auto Company', 'account_number' => '107614032891', 'bank_branch' => 'Sampath Bank Kandana'],
            ['payee_name' => 'Hwathiwanka Madushan', 'account_number' => '75714517', 'bank_branch' => 'Bank of Ceylon Akuressa'],
            ['payee_name' => 'I D S Priyantha', 'account_number' => '8570035081', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Isuru Bhanuka Amarathunga', 'account_number' => '8021037999', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'J A D A R Neelamani', 'account_number' => '8810015372', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'J Jeyakirupal', 'account_number' => '8001100804', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'J Jeyakirupal Pilimatalawa', 'account_number' => '8001100804', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'J L K M Liyanage', 'account_number' => '109852400185', 'bank_branch' => 'Sampath Bank Ja-Ela'],
            ['payee_name' => 'J L V S Liyanage', 'account_number' => '88026061', 'bank_branch' => 'Bank of Ceylon Kandana'],
            ['payee_name' => 'J M D V P Gerard', 'account_number' => '210020020203', 'bank_branch' => 'Hatton National Bank Pamunugama'],
            ['payee_name' => 'J.M.D.V.P. Gerard', 'account_number' => '210020020203', 'bank_branch' => 'Hatton National Bank Pamunugama'],
            ['payee_name' => 'K D V D A Wijesinghe', 'account_number' => '0085969512', 'bank_branch' => 'Bank of Ceylon Ahungalla'],
            ['payee_name' => 'K G R Premathilaka', 'account_number' => '044020208971', 'bank_branch' => 'Hatton National Bank Kandy'],
            ['payee_name' => 'K G S Priyadarshana', 'account_number' => '8009035535', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'K N K De Silva', 'account_number' => '006050004927', 'bank_branch' => 'Sampath Bank Kadawatha'],
            ['payee_name' => 'K P C M Fernando', 'account_number' => '109852744601', 'bank_branch' => 'Sampath Bank Ja-Ela'],
            ['payee_name' => 'K P W U B Senavirathna', 'account_number' => '119054711344', 'bank_branch' => 'Sampath Bank Galewela'],
            ['payee_name' => 'K Priyantha', 'account_number' => '71928230', 'bank_branch' => 'Bank of Ceylon Battaramulla'],
            ['payee_name' => 'K R D M Rajapaksha', 'account_number' => '8810037095', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'K S.Suraweera', 'account_number' => '203020055061', 'bank_branch' => 'Hatton National Bank Wadduwa'],
            ['payee_name' => 'K.A.D Tharindu', 'account_number' => '8150011356', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'K.R.D.M. Rajapaksha', 'account_number' => '8810037095', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'K.Rashitha Udara', 'account_number' => '8024905905', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'L D R C Madawala', 'account_number' => '131020157127', 'bank_branch' => 'Hatton National Bank Hendala'],
            ['payee_name' => 'L M T D Kumari', 'account_number' => '75892344', 'bank_branch' => 'Bank of Ceylon Hakmana'],
            ['payee_name' => 'L Sunil Jayarathne', 'account_number' => '8330048550', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'L. Sunil Jayarathne.', 'account_number' => '8330048550', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'L.H.H Nishadi De Silva', 'account_number' => '85569452', 'bank_branch' => 'Bank of Ceylon Ahungalla'],
            ['payee_name' => 'M A D Bandara', 'account_number' => '95975073', 'bank_branch' => 'Bank of Ceylon Kurunegala'],
            ['payee_name' => 'M K D Anura', 'account_number' => '0091919848', 'bank_branch' => 'Bank of Ceylon Matugama'],
            ['payee_name' => 'M K S P Gawarathanna', 'account_number' => '8017377382', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'M M G Dharmarathna', 'account_number' => '34559', 'bank_branch' => 'Bank of Ceylon Talatuoya'],
            ['payee_name' => 'M Ranjith Lal Priya De Zoysa', 'account_number' => '324200203202129', 'bank_branch' => 'Peoples Bank Seeduwa'],
            ['payee_name' => 'M T Mahmood', 'account_number' => '107357000214', 'bank_branch' => 'Sampath Bank Ragama'],
            ['payee_name' => 'M.A.A.S.T.Perera', 'account_number' => '273200140043260', 'bank_branch' => 'Peoples Bank Kadawata'],
            ['payee_name' => 'M.A.S.S. Perera', 'account_number' => '154200170007352', 'bank_branch' => 'Peoples Bank Balapitiya'],
            ['payee_name' => 'M.D.H.D.Soysa', 'account_number' => '112354455523', 'bank_branch' => 'Sampath Bank Kandy'],
            ['payee_name' => 'M.G.M.Mumthaz', 'account_number' => '8005634886', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'M.L.M.Yoosuf', 'account_number' => '114457325636', 'bank_branch' => 'Sampath Bank Maradana'],
            ['payee_name' => 'M.M.G.Dharmarathna', 'account_number' => '34559', 'bank_branch' => 'Bank of Ceylon Talatuoya'],
            ['payee_name' => 'M.P.C.Pathma Kumara', 'account_number' => '013020729190', 'bank_branch' => 'Hatton National Bank Galle'],
            ['payee_name' => 'Mahawatta I N E', 'account_number' => '13120060009', 'bank_branch' => 'Hatton National Bank Wattala'],
            ['payee_name' => 'Mnm Siran', 'account_number' => '8970033038', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'N G S Piumantha', 'account_number' => '145200150012954', 'bank_branch' => 'Peoples Bank Wellawatte'],
            ['payee_name' => 'N G S Piyumantha', 'account_number' => '8350032641', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Naushard Abdul Shard', 'account_number' => '8012899636', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Nimmika Sarangi Abeywickrama', 'account_number' => '8013671811', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'P A S Attiygala', 'account_number' => '8710004553', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'P D Ruwan Sampath Dayananda', 'account_number' => '149020082761', 'bank_branch' => 'Hatton National Bank Galewela'],
            ['payee_name' => 'P N A Shantha Peiris', 'account_number' => '033001057969102', 'bank_branch' => 'Seylan Bank Kottawa'],
            ['payee_name' => 'P Pathmanadan', 'account_number' => '107652037313', 'bank_branch' => 'Sampath Bank Kandana'],
            ['payee_name' => 'Perera G L C D', 'account_number' => '119020220777', 'bank_branch' => 'Hatton National Bank Kandana'],
            ['payee_name' => 'Pradeep Nalaka', 'account_number' => '8138329901', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'R A M M P Bandara', 'account_number' => '104652744200', 'bank_branch' => 'Sampath Bank Bandarawela'],
            ['payee_name' => 'R D Samarakoon', 'account_number' => '026200141687844', 'bank_branch' => 'Peoples Bank Gampaha'],
            ['payee_name' => 'R G R Tharanga', 'account_number' => '8015939070', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'R P Chandrathilake', 'account_number' => '8670025551', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'R P Priyantha', 'account_number' => '8300012616', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'R. K. Swarnalatha', 'account_number' => '8007634945', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'S A P C Madhuranga', 'account_number' => '7264020', 'bank_branch' => 'Bank of Ceylon Agalawatta'],
            ['payee_name' => 'S A W Samarakoon', 'account_number' => '8810005917', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'S D Kariyawasam', 'account_number' => '8011556769', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'S H Kosala Dhanesh', 'account_number' => '8021523812', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'S H N Udayanga', 'account_number' => '130200110043569', 'bank_branch' => 'Peoples Bank Hakmana'],
            ['payee_name' => 'S Kumara', 'account_number' => '024200170083651', 'bank_branch' => 'Peoples Bank Chilaw'],
            ['payee_name' => 'S N Basnayake', 'account_number' => '8019757472', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Salappu Arachchige Nilantha Dinesh', 'account_number' => '8003443466', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Sampth Kumara', 'account_number' => '024200170083651', 'bank_branch' => 'Peoples Bank Chilaw'],
            ['payee_name' => 'T G Pushpa Kumara', 'account_number' => '8040034816', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'T G S S Rathnayake', 'account_number' => '8023157428', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'The Mangrove Cave Pvt Ltd', 'account_number' => '035100100035540', 'bank_branch' => 'Peoples Bank Ambalangoda'],
            ['payee_name' => 'Thilina Perera Photography', 'account_number' => '1000386071', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Tour To Ceylon Pvt Ltd', 'account_number' => '1000958889', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Tuwan Raheem Ramlan', 'account_number' => '8230040579', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'W A N Asiri', 'account_number' => '110857882837', 'bank_branch' => 'Sampath Bank Chilaw'],
            ['payee_name' => 'W H M P Sovis', 'account_number' => '8422785901', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'W H M Roshan Asanga', 'account_number' => '107110187763', 'bank_branch' => 'NSB Kandy City Center'],
            ['payee_name' => 'W M K G T D Weerakkody', 'account_number' => '8147002919', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'W M R K Wijesinghe', 'account_number' => '106554432888', 'bank_branch' => 'Sampath Bank Minuwangoda'],
            ['payee_name' => 'W W H D K Weerasekara', 'account_number' => '100753771981', 'bank_branch' => 'Sampath Bank Kandy'],
            ['payee_name' => 'W. R. D. Rajanayake', 'account_number' => '000750119565', 'bank_branch' => 'Sampath Bank Kandy'],
            ['payee_name' => 'W.A Ajith Kumara', 'account_number' => '77200388405942', 'bank_branch' => 'Peoples Bank Weligama'],
            ['payee_name' => 'W.A.N.Asiri', 'account_number' => '110857882837', 'bank_branch' => 'Sampath Bank Chilaw'],
            ['payee_name' => 'W.M.D.I.B Parakumbura', 'account_number' => '72252564', 'bank_branch' => 'Bank of Ceylon Pothuhera'],
            ['payee_name' => 'W.M.P.N.Weerarathne', 'account_number' => '8225000923', 'bank_branch' => 'Com Bank'],
            ['payee_name' => 'Whm Roshan Asanga', 'account_number' => '112352861583', 'bank_branch' => 'Sampath Bank Kandy'],
            ['payee_name' => 'Wmdd Jayathissa', 'account_number' => '344200100015742', 'bank_branch' => 'Peoples Bank Melsiripura'],
            ['payee_name' => 'Y G T D Gamage', 'account_number' => '8450033181', 'bank_branch' => 'Com Bank'],
        ];

        $countryCode = 'LK';

        foreach ($drivers as $driver) {
            DriverBankDetail::updateOrCreate(
                [
                    'payee_name' => $driver['payee_name'],
                    'country_code' => $countryCode,
                ],
                [
                    'account_number' => $driver['account_number'],
                    'bank_branch' => $driver['bank_branch'],
                    'country_code' => $countryCode,
                    'is_active' => true,
                ]
            );
        }

        $this->command->info('✅ Sri Lanka Driver Bank Details imported successfully!');
        $this->command->info('📊 Total drivers: ' . count($drivers));
    }
}